[default]
dataloader_pin_memory = true

[fast_16gb]
layer_start = 2
dataloader_pin_memory = true

[low_vram]
blocks_to_swap = 0
gradient_checkpointing = true
unsloth_offload_checkpointing = true
dataloader_pin_memory = true

[32gb]
blocks_to_swap = 0
dataloader_pin_memory = true

[graft]
blocks_to_swap = 20
dataloader_pin_memory = true

[half]
blocks_to_swap = 8
dataloader_pin_memory = true
sample_ratio = 0.5

[quarter]
blocks_to_swap = 8
dataloader_pin_memory = true
sample_ratio = 0.25
