[default]
blocks_to_swap = 0

[low_vram]
gradient_checkpointing = true
unsloth_offload_checkpointing = true

[graft]
blocks_to_swap = 20

[half]
sample_ratio = 0.5

[quarter]
sample_ratio = 0.25

[tenth]
sample_ratio = 0.1