base_config = "base.toml"
dataset_config = "configs/dataset_config.toml"
network_module = "networks.postfix_anima"
network_dim = 16
caption_shuffle_variants = 8
checkpointing_epochs = 4
learning_rate = 2e-3
max_train_epochs = 8
save_every_n_epochs = 4
attn_mode = "flash"
cache_llm_adapter_outputs = true
trim_crossattn_kv = true
output_name = "anima_postfix"
