base_config = "base.toml"
dataset_config = "configs/dataset_config.toml"
network_module = "networks.postfix_anima"
network_dim = 16
network_args = ["mode=postfix"]
caption_shuffle_variants = 1
checkpointing_epochs = 1
learning_rate = 2e-3
max_train_epochs = 1
save_every_n_epochs = 1
attn_mode = "flash"
cache_llm_adapter_outputs = true
trim_crossattn_kv = true
output_name = "anima_postfix"
blocks_to_swap = 0
gradient_accumulation_steps=4