#!/usr/bin/env python3
"""Generate ``workflows/randoms.yaml`` from the tagger's groups + the corpus.

Booru tags are not independent (a pose needs its act, an act its mandatory
companion tags), so each entry here is a tag cluster, and both halves come
from data already in the repo:

* **which axis a tag sits on** — the Anima Tagger's ``groups.yaml``
  (loaded through :mod:`anime_tools.captions.tag_groups`). Slots are defined by
  *referencing* those groups, so re-curating the tagger taxonomy re-curates
  this pool. It also gives the block list: a companion from an
  identity-carrying group must come from ``__chara__``, never a random draw.
* **which tags travel together** — conditional co-occurrence over the caption
  master. A companion joins the cluster when ``P(companion | anchor) >= θ``
  inside the context captions.

``avoid:`` is the same statistic read the other way: two frequent tags that
*never* co-occur when independence predicts they should are incompatible, so
comfy_batch won't draw them into one prompt.

This file is pure mechanism. Everything corpus-specific — the slot→group
mapping, curated act/block/allow lists, context slice, crawl-pool path —
lives in ``workflows/randoms_build.yaml`` (gitignored, like the output).

Usage:
    python scripts/toolkits/build_randoms.py                    # writes workflows/randoms.yaml
    python scripts/toolkits/build_randoms.py --theta 0.5 --dry_run
"""

import argparse
import collections
import json
import pathlib
import sys

import yaml

from anime_tools.captions.position_clauses import parse_caption
from anime_tools.captions.tag_groups import load_groups

REPO = pathlib.Path(__file__).resolve().parents[2]
TAGGER = REPO / "models" / "captioners" / "anima-tagger-dbv4"
SPEC_PATH = REPO / "workflows" / "randoms_build.yaml"

HEADER = """\
# GENERATED by scripts/toolkits/build_randoms.py — edit that, or edit here and
# stop regenerating. Slots mirror the Anima Tagger's groups.yaml taxonomy;
# clusters and `avoid:` come from caption co-occurrence over {n_ctx} context
# captions (theta={theta}, <={max_companions} companions).
#
#   __random__            draw from the `default:` slots below
#   __random:position__   draw from one slot
#   __random:scene|body__ draw from the union of several
#
# An entry is a *cluster*: a tag plus the companions it practically always
# ships with, so a draw can't emit an act with its mandatory parts missing.
# comfy_batch drops tags already drawn by an earlier placeholder, and skips an
# entry whose `avoid:` names something already in the prompt.
#
# `weight:` is taste, measured: how much likelier the anchor is in the
# hand-picked image_dataset than in the raw crawl it was picked from (same
# context slice both sides, clipped to [{wlo}, {whi}]). 2.0 = drawn ~2x as
# often as a neutral entry; omitted = 1.0.
"""


def load_spec(path: pathlib.Path) -> dict:
    """The data half: slot taxonomy + curated lists, kept out of the repo."""
    if not path.exists():
        sys.exit(
            f"spec not found: {path}\n"
            "build_randoms.py is mechanism only — the slot mapping and curated "
            "tag lists live in that (gitignored) file. Restore it from a "
            "backup or another checkout."
        )
    spec = yaml.safe_load(path.read_text())
    required = (
        "slots",
        "default_slots",
        "position_slot",
        "position_acts",
        "core_companions",
        "block_groups",
        "block_tags",
        "block_tags_deliberate",
        "allow_anchors",
        "context",
        "pinned",
    )
    missing = [k for k in required if k not in spec]
    if missing:
        sys.exit(f"{path}: missing keys: {', '.join(missing)}")
    return spec


def load_captions(root: pathlib.Path) -> list[set]:
    """Tag sets from every caption sidecar under ``root`` (symlinks followed)."""
    caps = []
    for path in root.rglob("*.txt"):
        try:
            text = path.read_text(errors="ignore")
        except OSError:
            continue
        try:
            parsed = parse_caption(text)
            tags = list(parsed.bag)
            for clause in parsed.clauses:
                tags += list(clause.tags)
        except Exception:
            # A caption we can't parse is data, not a crash — fall back to the
            # flat bag and let the frequency floor drop the noise.
            tags = [t.strip() for t in text.replace(".", ",").split(",")]
        tag_set = {t.strip().lower() for t in tags if t.strip()}
        if tag_set:
            caps.append(tag_set)
    return caps


def selection_weights(
    ctx: list, context: set, args
) -> "collections.abc.Mapping[str, float]":
    """Per-tag draw weight from *revealed preference*.

    ``image_dataset`` (== dataset/selected) is the hand-picked keeper set;
    ``--retrieved`` is the raw crawl it was picked out of, same artists. A tag
    that is X times likelier in the keepers than in the crawl is a tag that
    made the curator keep the image — measured within the same context slice
    on both sides, so "picks fewer such images overall" can't masquerade as
    per-tag taste.

    Weights are clipped to [lo, hi]: the two pools were captioned at different
    times, so an extreme ratio is as likely to be tagging drift as taste (no
    real preference is 22x). Clipping keeps the bias while capping what any
    one confounded tag can do.

    A missing crawl dir (volume not mounted) degrades to neutral weights.
    """
    root = pathlib.Path(args.retrieved) if args.retrieved else None
    if root is None or not root.exists():
        print(f"note: no retrieved pool at {args.retrieved!r} — weights stay 1.0")
        return collections.defaultdict(lambda: 1.0)
    ret = [c for c in load_captions(root) if c & context]
    if len(ret) < 500:
        print(f"note: retrieved pool too small ({len(ret)}) — weights stay 1.0")
        return collections.defaultdict(lambda: 1.0)
    cs = collections.Counter(t for c in ctx for t in c)
    cr = collections.Counter(t for c in ret for t in c)
    ns, nr = len(ctx), len(ret)
    lo, hi = args.weight_clip
    weights: dict[str, float] = collections.defaultdict(lambda: 1.0)
    for t, ks in cs.items():
        if ks + cr.get(t, 0) < args.weight_min_n:
            continue
        lift = (ks / ns) / ((cr.get(t, 0) + 1) / (nr + 1))
        weights[t] = round(min(hi, max(lo, lift)), 2)
    print(f"selection weights: {len(weights)} tags vs {len(ret)} crawl captions")
    return weights


def build(args, spec: dict) -> dict:
    groups = load_groups(args.groups)
    tag_to_group = groups.tag_to_group
    vocab = json.loads(pathlib.Path(args.vocab).read_text())
    general = {t["name"] for t in vocab["tags"] if t["category"] == "general"}

    caps = load_captions(pathlib.Path(args.captions))
    if not caps:
        sys.exit(f"no captions under {args.captions}")
    context = set(spec["context"])
    ctx = [c for c in caps if c & context] or caps
    position_slot = spec["position_slot"]
    acts = set(spec["position_acts"])
    core_companions = set(spec["core_companions"])
    block_groups = set(spec["block_groups"])
    blocked_tags = (
        set(spec["block_tags"])
        | set(spec["block_tags_deliberate"])
        | set(spec["pinned"])
        | {t.strip() for t in args.exclude if t.strip()}
    )

    count = collections.Counter(t for c in ctx for t in c)
    n_ctx = len(ctx)
    act_groups = set(spec["slots"][position_slot])

    def is_act(tag: str) -> bool:
        """Only an act earns the mandatory-companion carve-out below."""
        return tag_to_group.get(tag) in act_groups

    def companions(anchor: str, slot: str) -> list[str]:
        """Tags that show up with ``anchor`` often enough to be part of it.

        Frequency alone is not company: a tag that rides 60% of every caption
        in this corpus clears any P(c|anchor) bar without telling us anything
        about the anchor. The lift gate keeps only companions the anchor
        genuinely *enriches* — except the spec's ``core_companions``, which
        are ambient enough corpus-wide that lift under-scores them exactly
        where they are mandatory, so for those the P>=theta bar alone decides.

        Position tags are filtered out everywhere but the position slot for
        the same reason they are as anchors: a genuinely co-occurring position
        tag drawn by another slot hands the prompt a second position that
        fights the first.
        """
        together = collections.Counter(t for c in ctx if anchor in c for t in c)
        ranked = sorted(
            (
                (k / count[anchor], t)
                for t, k in together.items()
                if t != anchor
                and (slot == position_slot or t not in acts)
                and t in general
                and t not in blocked_tags
                and tag_to_group.get(t) not in block_groups
                and k / count[anchor] >= args.theta
                and (
                    (t in core_companions and is_act(anchor))
                    or (k / count[anchor]) / (count[t] / n_ctx) >= args.min_lift
                )
            ),
            reverse=True,
        )
        return [t for _p, t in ranked[: args.max_companions]]

    # Anchors first, so `avoid` can be scoped to tags another slot can actually draw.
    anchors: dict[str, list[str]] = {}
    for slot, group_names in spec["slots"].items():
        pool = [
            t
            for name in group_names
            for t in (groups.by_name(name).tags if groups.by_name(name) else ())
            if t in general and t not in blocked_tags and count[t] >= args.min_anchor
        ]
        # A position tag anchors the position slot and nothing else — the
        # taxonomy may file one under another group, but drawing it into a
        # different slot would hand the prompt a second, conflicting position.
        pool = [t for t in pool if (t in acts) == (slot == position_slot)]
        pool += [
            t
            for t in spec["allow_anchors"].get(slot, [])
            if t in general and count[t] >= args.min_anchor
        ]
        anchors[slot] = sorted(set(pool), key=lambda t: -count[t])[: args.max_anchors]

    def avoid_for(slot: str, anchor: str) -> list[str]:
        """Frequent tags from other slots that never co-occur with ``anchor``.

        Zero co-occurrence only means something when independence predicts
        several — otherwise a rare pair is just unobserved, not incompatible.
        """
        if count[anchor] < args.avoid_min:
            return []
        with_anchor = [c for c in ctx if anchor in c]
        out = []
        for other, others in anchors.items():
            if other == slot:
                continue
            for tag in others:
                if count[tag] < args.avoid_min:
                    continue
                expected = count[anchor] * count[tag] / n_ctx
                if expected >= args.avoid_expected and not any(
                    tag in c for c in with_anchor
                ):
                    out.append(tag)
        return sorted(set(out), key=lambda t: -count[t])[: args.max_avoid]

    taste = selection_weights(ctx, context, args)

    pool = {}
    for slot, slot_anchors in anchors.items():
        entries, seen = [], set()
        for anchor in slot_anchors:
            tags = [anchor] + companions(anchor, slot)
            # `lying, on back, …` and `on back, lying, …` are the same draw
            # wearing a different anchor — keep the more frequent one only.
            key = frozenset(tags)
            if key in seen:
                continue
            seen.add(key)
            entry = {"tags": tags}
            avoid = avoid_for(slot, anchor)
            if avoid:
                entry["avoid"] = avoid
            if taste[anchor] != 1.0:
                entry["weight"] = taste[anchor]
            entries.append(entry)
        pool[slot] = entries
    return {"pool": pool, "n_ctx": n_ctx}


def render(pool: dict, n_ctx: int, default_slots: list, args) -> str:
    """Emit YAML by hand — the header comments are the point of this file."""
    out = [
        HEADER.format(
            n_ctx=n_ctx,
            theta=args.theta,
            max_companions=args.max_companions,
            wlo=args.weight_clip[0],
            whi=args.weight_clip[1],
        )
    ]
    present = [s for s in default_slots if pool.get(s)]
    out.append(f"\ndefault: [{', '.join(present)}]\n")
    for slot, entries in pool.items():
        kind = "default draw" if slot in default_slots else "by name only"
        out.append(f"\n# --- {slot} ({len(entries)} entries, {kind}) ---")
        out.append(f"{slot}:")
        for entry in entries:
            tags = ", ".join(entry["tags"])
            if entry.get("avoid") or entry.get("weight"):
                out.append(f'  - tags: "{tags}"')
                if entry.get("avoid"):
                    out.append(f"    avoid: [{', '.join(entry['avoid'])}]")
                if entry.get("weight"):
                    out.append(f"    weight: {entry['weight']}")
            else:
                out.append(f'  - "{tags}"')
    return "\n".join(out) + "\n"


def main():
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("--spec", default=str(SPEC_PATH), help="Data half (gitignored).")
    p.add_argument("--groups", default=str(TAGGER / "groups.yaml"))
    p.add_argument("--vocab", default=str(TAGGER / "vocab.json"))
    p.add_argument("--captions", default=str(REPO / "image_dataset"))
    p.add_argument("--out", default=str(REPO / "workflows" / "randoms.yaml"))
    p.add_argument("--exclude", nargs="*", default=[], help="Extra tags to block.")
    p.add_argument(
        "--retrieved",
        default=None,
        help="Override the spec's crawl-pool dir; missing dir = neutral weights.",
    )
    p.add_argument("--weight_clip", type=float, nargs=2, default=(0.5, 2.0))
    p.add_argument("--weight_min_n", type=int, default=40)
    p.add_argument("--theta", type=float, default=0.6)
    p.add_argument("--min_lift", type=float, default=1.25)
    p.add_argument("--max_companions", type=int, default=4)
    p.add_argument("--min_anchor", type=int, default=15)
    p.add_argument("--max_anchors", type=int, default=24)
    p.add_argument("--avoid_min", type=int, default=25)
    p.add_argument("--avoid_expected", type=float, default=3.0)
    p.add_argument("--max_avoid", type=int, default=8)
    p.add_argument("--dry_run", action="store_true")
    args = p.parse_args()

    spec = load_spec(pathlib.Path(args.spec))
    if args.retrieved is None:
        args.retrieved = spec.get("retrieved", "")

    built = build(args, spec)
    text = render(built["pool"], built["n_ctx"], spec["default_slots"], args)
    sizes = ", ".join(f"{s}={len(e)}" for s, e in built["pool"].items())
    print(f"context captions: {built['n_ctx']} | {sizes}")
    if args.dry_run:
        print(text)
        return
    pathlib.Path(args.out).write_text(text)
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
